server:
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 7bu57cgf
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: HikariCP-CUS

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
mybatis-plus:
  mapper-locations: classpath*:resources/mapper/**/*.xml
logging:
  config: classpath:logback-spring.xml
